import * as vscode from 'vscode';
import axios from 'axios';

import { Config, constructUri, Package } from '../types/common';

type Symbols = { [tag: string]: vscode.Location[]; };

export default class SymbolsClient {
    private config: Config;

    // A cache of the package-local symbols for each package as generated by the
    // ctags program. Lazy-loaded.
    private locals: { [pkgName: string]: Thenable<Symbols>; };

    // A list of all exported symbols across all pacakges, generated from the
    // Debian 'symbols' indexes.
    private globals: Thenable<Symbols>;

    constructor(config: Config) {
        this.config = config;
        this.locals = {};

        // Download globals index
        const url = vscode.Uri.joinPath(this.config.meta, this.config.distribution, "symbols.txt");
        this.globals = axios
            .get(url.toString(), { responseType: 'text' })
            .then(res => {
                const syms: Symbols = {};
                let pkg = undefined;
                let name = undefined;
                for (const line of res.data.split("\n")) {
                    if (line.startsWith("### ")) {
                        pkg = line.split(" ")[1];
                    } else if (line.startsWith(" - ") && pkg && name) {
                        const parts = line.substring(3).split(/;"|\t/);
                        const uri = constructUri(this.config, pkg, parts[0]);
                        const range = new vscode.Position(Number(parts[1]) - 1, 0);
                        syms[name] ||= [];
                        syms[name].push(new vscode.Location(uri, range));
                    } else if (line.startsWith(" ")) {
                        name = line.split(/[ @]/)[1];
                    }
                }
                return syms;
            })
            .catch(err => {
                throw vscode.FileSystemError.Unavailable(err);
            });
    }

    listPackageSymbols(pkg: Package): Thenable<Symbols> {
        if (!(pkg.name in this.locals)) {
            const filename = pkg.name + "_" + pkg.version + ":" + pkg.epoch + ".tags";
            const url = vscode.Uri.joinPath(this.config.ls, this.config.distribution, pkg.name, filename);
            return axios
                .get(url.toString(), { responseType: 'text' })
                .then(res => {
                    const syms: Symbols = {};
                    for (const line of res.data.split("\n")) {
                        const parts = line.split(/;"|\t/);
                        const name = parts[0];
                        const uri = constructUri(this.config, pkg.name, parts[1]);
                        const range = new vscode.Position(Number(parts[2]) - 1, 0);
                        syms[name] ||= [];
                        syms[name].push(new vscode.Location(uri, range));
                    }
                    return syms;
                })
                .catch(err => {
                    throw vscode.FileSystemError.Unavailable(err);
                });
        }
        return this.locals[pkg.name];
    }

    listGlobalSymbols(): Thenable<Symbols> {
        return this.globals;
    }
}
