#!/bin/bash

set -euf -o pipefail

TAG="src-codes/grep"
NAME="src-grep"
HOSTNAME="grep.src.codes"
IP6="2605:6400:5ba2::c0de:2"
DATADIR="/data/grep"
SRCDIR="/var/src.codes"

docker build --tag "$TAG" --pull "$(dirname $0)"

STALE="$(docker container ls --all --quiet --filter name=$NAME)"
if [[ "$STALE" ]]; then
    docker container rm "$NAME"
fi

docker run -dit \
    --mount "type=bind,source=$DATADIR,target=/data" \
    --mount "type=bind,source=$SRCDIR,target=/var/src.codes,readonly" \
    --name "$NAME" \
    --hostname "$HOSTNAME" \
    --network public \
    --ip6 "$IP6" \
    "$TAG"

docker image prune --force
