#!/bin/bash

set -euf -o pipefail

IMAGE="ghcr.io/btidor/src.codes:${1-latest}"
NAME="src-grep"
HOSTNAME="grep.src.codes"
IP6="2605:6400:5ba2::c0de:2"
BULKDIR="/data/grep"
FASTDIR="/var/grep"

docker pull "$IMAGE"

STALE="$(docker container ls --all --quiet --filter name=$NAME)"
if [[ "$STALE" ]]; then
    docker container rm --force "$NAME"
fi

docker run -dit \
    --mount "type=bind,source=$BULKDIR,target=/bulk,readonly" \
    --mount "type=bind,source=$FASTDIR,target=/fast,readonly" \
    --name "$NAME" \
    --hostname "$HOSTNAME" \
    --network public \
    --ip6 "$IP6" \
    "$IMAGE" \
    /var/src.codes/grep serve \
    -cert /bulk/tls/certificate.pem \
    -key /bulk/tls/key.pem \
    -fastData /fast \
    -bulkData /bulk

docker image prune --force
