#!/usr/bin/env python3
#
# Injects TEMPLATE into CONTENTS at a "BUILD->INSERT_XXX" comment.

import re
import sys

PATTERN = r'[{[] */\* *BUILD->INSERT_[A-Z_]+ *\*/ *[}\]]'

if len(sys.argv) != 3:
    print(f"usage: {sys.argv[0]} TEMPLATE CONTENTS")
    exit(1)

with open(sys.argv[1]) as f:
    template = f.read()

with open(sys.argv[2]) as f:
    contents = f.read()

escaped = contents.replace('\\', '\\\\')
escaped = escaped.replace('`', '\\`')
escaped = escaped.replace('$', '\\$')

wrapped = 'JSON.parse(`' + escaped + '`)'
wrapped = wrapped.replace('\\', '\\\\') # see re.sub docs
replaced = re.sub(PATTERN, wrapped, template)

if replaced == template:
    print("Error: no substitution found!")
    exit(2)

with open(sys.argv[1], 'w') as f:
    f.write(replaced)
