#!/bin/bash

set -veuf -o pipefail

export PROJECT_BASE="$(dirname $(dirname $(realpath $0)))"
export BUILD_DIR="$PROJECT_BASE/api-out"

mkdir -p "$BUILD_DIR"

# Copy robots.txt
cp "$PROJECT_BASE/infra/robots.txt" "$BUILD_DIR/robots.txt"

# Other than the robots.txt file, $BUILD_DIR empty because files take precedence
# over rewrite rules in vercel.json and we don't want to serve our source code.
