[package]
name = "api"
version = "0.1.0"
edition = "2018"

[dependencies]
http = "0.1"
reqwest = { version = "0.11", features = ["blocking"] }
vercel_lambda = "*"
fzf = { path = "../fzf" }

[[bin]]
name = "fzf"
path = "fzf.rs"
