name: grep
on:
  push: {}
  workflow_dispatch: {}
concurrency: grep
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
