name: grep
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
concurrency: grep
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          file: grep/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
