name: grep
on:
  push: {}
  workflow_dispatch: {}
concurrency: grep
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Compute Docker metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref_name == github.event.repository.default_branch }}
            type=ref,event=branch,enable=${{ github.ref_name != github.event.repository.default_branch }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          file: grep/Dockerfile
          push: true
          build-args: COMMIT=${{ github.sha }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
