name: Publisher
on:
  schedule:
    - cron: '17 07 * * *'
  workflow_dispatch: {}
concurrency: publisher
jobs:
  run-publisher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.4

      - name: Install Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y binutils universal-ctags

      - name: Run publisher
        run: go run -v ./publisher/cmd
        env:
          DATABASE: ${{ secrets.DATABASE }}
          B2_LS_KEY: ${{ secrets.B2_LS_KEY }}
          B2_CAT_KEY: ${{ secrets.B2_CAT_KEY }}
          B2_META_KEY: ${{ secrets.B2_META_KEY }}

      - name: Deploy index to grep
        env:
          ZEROKUBE_TOKEN: ${{ secrets.ZEROKUBE_TOKEN }}
        run: |
          curl https://vm1.src.codes/hook \
            --http1.1 --data grep.update \
            --header "Authorization: Bearer $ZEROKUBE_TOKEN"

      - name: Deploy index to fzf
        env:
          ZEROKUBE_TOKEN: ${{ secrets.ZEROKUBE_TOKEN }}
        run: |
          curl https://vm1.src.codes/deploy \
            --http1.1 --data fzf \
            --header "Authorization: Bearer $ZEROKUBE_TOKEN"
