name: publisher
on:
  schedule:
    - cron: '17 07 * * *'
  workflow_dispatch: {}
jobs:
  run-publisher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install Dependencies
        run: |
          sudo cp $GITHUB_WORKSPACE/.devcontainer/bazel.gpg /usr/share/keyrings/
          sudo cp $GITHUB_WORKSPACE/.devcontainer/bazel.list /etc/apt/sources.list.d/
          sudo apt update -y
          sudo apt install -y bazel-4.0.0 binutils universal-ctags
          git clone https://github.com/livegrep/livegrep.git $GITHUB_WORKSPACE/livegrep
          (cd $GITHUB_WORKSPACE/livegrep && bazel-4.0.0 build //...)
          sudo cp $GITHUB_WORKSPACE/livegrep/bazel-bin/src/tools/codesearch /usr/local/bin

      - name: Run publisher
        run: go run -v ./cmd
        working-directory: ./publisher
        env:
          DATABASE: ${{ secrets.DATABASE }}
          B2_LS_KEY: ${{ secrets.B2_LS_KEY }}
          B2_CAT_KEY: ${{ secrets.B2_CAT_KEY }}
          B2_META_KEY: ${{ secrets.B2_META_KEY }}

concurrency: publisher-mutex
