name: publisher
on:
  schedule:
    - cron: '17 07 * * *'
  workflow_dispatch: {}
jobs:
  run-publisher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install Dependencies
        run: sudo apt install -y universal-ctags

      - name: Run publisher
        run: go run -v ./cmd
        working-directory: ./publisher
        env:
          DATABASE: ${{ secrets.DATABASE }}
          B2_LS_KEY: ${{ secrets.B2_LS_KEY }}
          B2_CAT_KEY: ${{ secrets.B2_CAT_KEY }}
          B2_META_KEY: ${{ secrets.B2_META_KEY }}

concurrency: publisher-mutex
