name: publisher
on:
  schedule:
    - cron: '17 07 * * *'
  workflow_dispatch: {}
jobs:
  run-publisher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y binutils universal-ctags

      - name: Run publisher
        run: go run -v ./publisher/cmd
        env:
          DATABASE: ${{ secrets.DATABASE }}
          B2_LS_KEY: ${{ secrets.B2_LS_KEY }}
          B2_CAT_KEY: ${{ secrets.B2_CAT_KEY }}
          B2_META_KEY: ${{ secrets.B2_META_KEY }}

      - name: Deploy latest index
        env:
          ZEROKUBE_TOKEN: ${{ secrets.ZEROKUBE_TOKEN }}
        run: |
          curl https://vm1.src.codes/hook \
            --request POST --data grep.update \
            --header "Authorization: Bearer $ZEROKUBE_TOKEN"

concurrency: publisher-mutex
